GET http://localhost:5000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4xMjMiLCJwYXNzd29yZCI6IiQyYiQxMCRYM0pFOHY4bVdtYU5tZ0VqelExcFR1SDZQL2tPLnc0eTNnLk5RdlJQbklVWTJGTGNjZXh5SyIsImVtYWlsIjoiam9obmRvZTEyM0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NjYwMjAyMzUsImV4cCI6MTY2NjAyMDgzNX0.WHHhNY5hp8H5BeNMkEOgy9h8kl4gpzg7yZVz7hjyQu8